"use client";

import { useMemo, useState } from "react";
import { AskResponse } from "@/lib/types";

declare global {
  var measureTextWidth: ((font: string, text: string) => number) | undefined;
}

type DocumentKey =
  | "riskAssessmentDraft"
  | "tbmBriefing"
  | "tbmLogDraft"
  | "safetyEducationRecordDraft"
  | "kakaoMessage";

type EditableDocument = {
  key: DocumentKey;
  title: string;
  description: string;
  fileBase: string;
};

type RhwpModule = typeof import("@rhwp/core");

let rhwpModulePromise: Promise<RhwpModule> | null = null;

const documentMeta: EditableDocument[] = [
  {
    key: "riskAssessmentDraft",
    title: "위험성평가표",
    description: "공정, 유해위험요인, 감소대책, 잔여위험을 정리합니다.",
    fileBase: "risk-assessment"
  },
  {
    key: "tbmBriefing",
    title: "TBM 브리핑",
    description: "작업반장이 작업 전 그대로 읽을 수 있는 전달문입니다.",
    fileBase: "tbm-briefing"
  },
  {
    key: "tbmLogDraft",
    title: "TBM 회의록",
    description: "작업내용, 전달사항, 참석자 확인을 기록합니다.",
    fileBase: "tbm-log"
  },
  {
    key: "safetyEducationRecordDraft",
    title: "안전교육일지",
    description: "교육명, 대상, 내용, 확인자, 후속 교육을 남깁니다.",
    fileBase: "safety-education"
  },
  {
    key: "kakaoMessage",
    title: "현장 공유 메시지",
    description: "카카오톡·문자·단체방에 붙여넣기 좋은 축약본입니다.",
    fileBase: "field-message"
  }
];

function sanitizeFileName(value: string) {
  return value.replace(/[\\/:*?"<>|]/g, "-").replace(/\s+/g, "-").slice(0, 80) || "safeguard";
}

function downloadBlob(blob: Blob, fileName: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function buildHtml(title: string, body: string) {
  return `<!doctype html>
<html lang="ko">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)}</title>
  <style>
    body { font-family: "Noto Sans KR", "Malgun Gothic", sans-serif; color: #1d2430; margin: 40px; line-height: 1.65; }
    h1 { font-size: 24px; margin: 0 0 18px; }
    pre { white-space: pre-wrap; font-family: inherit; font-size: 14px; }
    .meta { color: #657084; font-size: 12px; margin-bottom: 22px; }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  <div class="meta">Generated by SafeGuard</div>
  <pre>${escapeHtml(body)}</pre>
</body>
</html>`;
}

async function loadRhwp() {
  if (!rhwpModulePromise) {
    rhwpModulePromise = (async () => {
      let canvasContext: CanvasRenderingContext2D | null = null;
      let lastFont = "";
      globalThis.measureTextWidth = (font: string, text: string) => {
        if (!canvasContext) {
          canvasContext = document.createElement("canvas").getContext("2d");
        }
        if (!canvasContext) return text.length * 12;
        if (font !== lastFont) {
          canvasContext.font = font;
          lastFont = font;
        }
        return canvasContext.measureText(text).width;
      };

      const rhwp = await import("@rhwp/core");
      await rhwp.default({ module_or_path: "/rhwp_bg.wasm" });
      return rhwp;
    })();
  }

  return rhwpModulePromise;
}

async function buildHwpxWithRhwp(body: string) {
  const { HwpDocument } = await loadRhwp();
  const document = HwpDocument.createEmpty();
  try {
    document.createBlankDocument();
    document.insertText(0, 0, 0, body);
    const exported = document.exportHwpx();
    const buffer = new ArrayBuffer(exported.byteLength);
    new Uint8Array(buffer).set(exported);
    return new Blob([buffer], { type: "application/hwp+zip" });
  } finally {
    document.free();
  }
}

function buildCombinedText(values: Record<DocumentKey, string>) {
  return documentMeta.map((item) => `# ${item.title}\n\n${values[item.key]}`).join("\n\n---\n\n");
}

export function WorkpackEditor({ data }: { data: AskResponse }) {
  const initialValues = useMemo<Record<DocumentKey, string>>(
    () => ({
      riskAssessmentDraft: data.deliverables.riskAssessmentDraft,
      tbmBriefing: data.deliverables.tbmBriefing,
      tbmLogDraft: data.deliverables.tbmLogDraft,
      safetyEducationRecordDraft: data.deliverables.safetyEducationRecordDraft,
      kakaoMessage: data.deliverables.kakaoMessage
    }),
    [data]
  );
  const [selectedKey, setSelectedKey] = useState<DocumentKey>("riskAssessmentDraft");
  const [values, setValues] = useState<Record<DocumentKey, string>>(initialValues);
  const [hwpxStatus, setHwpxStatus] = useState<"idle" | "building" | "error">("idle");
  const selected = documentMeta.find((item) => item.key === selectedKey) || documentMeta[0];
  const selectedText = values[selected.key];
  const baseName = sanitizeFileName(`${data.scenario.companyName}-${selected.fileBase}`);

  function updateValue(value: string) {
    setValues((current) => ({ ...current, [selected.key]: value }));
  }

  function downloadText() {
    downloadBlob(new Blob([selectedText], { type: "text/plain;charset=utf-8" }), `${baseName}.txt`);
  }

  function downloadJson() {
    const payload = {
      title: selected.title,
      scenario: data.scenario,
      document: selectedText,
      generatedAt: new Date().toISOString()
    };
    downloadBlob(new Blob([JSON.stringify(payload, null, 2)], { type: "application/json;charset=utf-8" }), `${baseName}.json`);
  }

  function downloadHtml() {
    downloadBlob(new Blob([buildHtml(selected.title, selectedText)], { type: "text/html;charset=utf-8" }), `${baseName}.html`);
  }

  function downloadJpg() {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1240" height="1754">
      <rect width="100%" height="100%" fill="#fffaf1"/>
      <foreignObject x="60" y="60" width="1120" height="1634">
        <div xmlns="http://www.w3.org/1999/xhtml" style="font-family: 'Malgun Gothic', sans-serif; color:#1d2430;">
          <h1 style="font-size:36px;margin:0 0 24px;">${escapeHtml(selected.title)}</h1>
          <pre style="white-space:pre-wrap;font-family:inherit;font-size:22px;line-height:1.55;">${escapeHtml(selectedText)}</pre>
        </div>
      </foreignObject>
    </svg>`;
    const image = new Image();
    const svgUrl = URL.createObjectURL(new Blob([svg], { type: "image/svg+xml;charset=utf-8" }));
    image.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = 1240;
      canvas.height = 1754;
      const context = canvas.getContext("2d");
      if (!context) return;
      context.fillStyle = "#fffaf1";
      context.fillRect(0, 0, canvas.width, canvas.height);
      context.drawImage(image, 0, 0);
      canvas.toBlob((blob) => {
        if (blob) downloadBlob(blob, `${baseName}.jpg`);
        URL.revokeObjectURL(svgUrl);
      }, "image/jpeg", 0.92);
    };
    image.src = svgUrl;
  }

  async function downloadHwpx() {
    setHwpxStatus("building");
    try {
      const blob = await buildHwpxWithRhwp(`${selected.title}\n\n${selectedText}`);
      downloadBlob(blob, `${baseName}.hwpx`);
      setHwpxStatus("idle");
    } catch (error) {
      console.error("rhwp HWPX export failed", error);
      setHwpxStatus("error");
    }
  }

  function downloadAll() {
    const combined = buildCombinedText(values);
    downloadBlob(new Blob([combined], { type: "text/plain;charset=utf-8" }), `${sanitizeFileName(data.scenario.companyName)}-safeguard-workpack.txt`);
  }

  function printPdf() {
    const popup = window.open("", "_blank", "width=900,height=1100");
    if (!popup) return;
    popup.document.write(buildHtml(selected.title, selectedText));
    popup.document.close();
    popup.focus();
    popup.print();
  }

  return (
    <section className="workpack-shell" id="workpack">
      <div className="workpack-sidebar card list">
        <div>
          <div className="eyebrow">SafeGuard Workpack</div>
          <div className="h2">오늘 문서팩</div>
          <p className="muted">현장에서 바로 수정하고 내려받을 수 있는 작업 전 산출물입니다.</p>
        </div>
        <div className="doc-tab-list">
          {documentMeta.map((item) => (
            <button
              key={item.key}
              type="button"
              className={`doc-tab ${item.key === selected.key ? "active" : ""}`}
              onClick={() => setSelectedKey(item.key)}
            >
              <strong>{item.title}</strong>
              <span>{item.description}</span>
            </button>
          ))}
        </div>
        <button type="button" className="button secondary" onClick={downloadAll}>전체 TXT 다운로드</button>
      </div>

      <div className="card document-editor">
        <div className="document-toolbar">
          <div>
            <div className="eyebrow">Editable document</div>
            <div className="h2">{selected.title}</div>
            <p className="muted">{selected.description}</p>
          </div>
          <div className="download-bar">
            <button type="button" className="button secondary" onClick={downloadText}>TXT</button>
            <button type="button" className="button secondary" onClick={downloadJson}>JSON</button>
            <button type="button" className="button secondary" onClick={downloadHtml}>HTML</button>
            <button type="button" className="button secondary" onClick={downloadJpg}>JPG</button>
            <button type="button" className="button secondary" onClick={printPdf}>PDF</button>
            <button type="button" className="button" onClick={downloadHwpx} disabled={hwpxStatus === "building"}>
              {hwpxStatus === "building" ? "HWPX 생성 중" : "HWPX"}
            </button>
          </div>
        </div>
        {hwpxStatus === "error" ? (
          <p className="export-error">HWPX 생성 중 오류가 발생했습니다. TXT 또는 HTML로 먼저 내려받아 주세요.</p>
        ) : null}
        <textarea
          className="document-textarea"
          value={selectedText}
          onChange={(event) => updateValue(event.target.value)}
          aria-label={`${selected.title} 편집`}
        />
      </div>
    </section>
  );
}
