"use client";

import { useMemo, useState } from "react";
import { AskResponse } from "@/lib/types";

declare global {
  var measureTextWidth: ((font: string, text: string) => number) | undefined;
}

type DocumentKey =
  | "riskAssessmentDraft"
  | "tbmBriefing"
  | "tbmLogDraft"
  | "safetyEducationRecordDraft"
  | "kakaoMessage";

type EditableDocument = {
  key: DocumentKey;
  title: string;
  description: string;
  fileBase: string;
};

type RhwpModule = typeof import("@rhwp/core");
type SheetRow = {
  document: string;
  section: string;
  item: string;
  content: string;
};

let rhwpModulePromise: Promise<RhwpModule> | null = null;

const documentMeta: EditableDocument[] = [
  {
    key: "riskAssessmentDraft",
    title: "위험성평가표",
    description: "KOSHA 절차에 맞춰 사전준비, 위험요인, 감소대책, 조치 확인을 정리합니다.",
    fileBase: "risk-assessment"
  },
  {
    key: "tbmBriefing",
    title: "TBM/작업 전 안전점검회의",
    description: "작업내용, 위험요인, 안전대책, 참석자 확인을 브리핑 형식으로 정리합니다.",
    fileBase: "tbm-briefing"
  },
  {
    key: "tbmLogDraft",
    title: "TBM 기록",
    description: "작업일지·모바일 앱·사진·영상 기록까지 함께 남기는 회의 기록입니다.",
    fileBase: "tbm-log"
  },
  {
    key: "safetyEducationRecordDraft",
    title: "안전보건교육 기록",
    description: "교육대상, 교육내용, 확인방법, 후속 교육 추천을 분리해 남깁니다.",
    fileBase: "safety-education"
  },
  {
    key: "kakaoMessage",
    title: "현장 공유 메시지",
    description: "카카오톡·문자·단체방에 붙여넣기 좋은 축약본입니다.",
    fileBase: "field-message"
  }
];

function sanitizeFileName(value: string) {
  return value.replace(/[\\/:*?"<>|]/g, "-").replace(/\s+/g, "-").slice(0, 80) || "safeguard";
}

function downloadBlob(blob: Blob, fileName: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function buildHtml(title: string, body: string) {
  return `<!doctype html>
<html lang="ko">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)}</title>
  <style>
    body { font-family: "Noto Sans KR", "Malgun Gothic", sans-serif; color: #1d2430; margin: 40px; line-height: 1.65; }
    h1 { font-size: 24px; margin: 0 0 18px; }
    pre { white-space: pre-wrap; font-family: inherit; font-size: 14px; }
    .meta { color: #657084; font-size: 12px; margin-bottom: 22px; }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  <div class="meta">Generated by SafeGuard</div>
  <pre>${escapeHtml(body)}</pre>
</body>
</html>`;
}

function parseSheetRows(title: string, body: string): SheetRow[] {
  const rows: SheetRow[] = [];
  let section = "기본정보";
  let itemNumber = 1;

  body.split(/\r?\n/).forEach((rawLine) => {
    const line = rawLine.trim();
    if (!line) return;

    const sectionMatch = line.match(/^\[(.+)\]$/);
    if (sectionMatch) {
      section = sectionMatch[1];
      itemNumber = 1;
      return;
    }

    const keyed = line.match(/^([^:：]+)[:：]\s*(.+)$/);
    const numbered = line.match(/^(\d+)\.\s*(.+)$/);
    const bullet = line.match(/^[-ㆍ]\s*(.+)$/);

    if (keyed) {
      rows.push({ document: title, section, item: keyed[1].trim(), content: keyed[2].trim() });
      return;
    }
    if (numbered) {
      rows.push({ document: title, section, item: numbered[1].trim(), content: numbered[2].trim() });
      return;
    }
    if (bullet) {
      rows.push({ document: title, section, item: String(itemNumber), content: bullet[1].trim() });
      itemNumber += 1;
      return;
    }

    rows.push({ document: title, section, item: String(itemNumber), content: line });
    itemNumber += 1;
  });

  return rows;
}

function buildRowsForDocument(meta: EditableDocument, values: Record<DocumentKey, string>) {
  return parseSheetRows(meta.title, values[meta.key]);
}

function buildRowsForAll(values: Record<DocumentKey, string>) {
  return documentMeta.flatMap((meta) => buildRowsForDocument(meta, values));
}

function escapeCell(value: string) {
  return `"${value.replace(/"/g, "\"\"")}"`;
}

function buildDelimited(rows: SheetRow[], delimiter: "," | "\t") {
  const header = ["문서", "섹션", "항목", "내용"];
  const body = rows.map((row) => [row.document, row.section, row.item, row.content]
    .map((value) => delimiter === "," ? escapeCell(value) : value.replace(/\t/g, " ").replace(/\r?\n/g, " "))
    .join(delimiter));
  return [header.join(delimiter), ...body].join("\n");
}

function buildExcelHtml(title: string, rows: SheetRow[]) {
  const tableRows = rows.map((row) => `<tr><td>${escapeHtml(row.document)}</td><td>${escapeHtml(row.section)}</td><td>${escapeHtml(row.item)}</td><td>${escapeHtml(row.content)}</td></tr>`).join("");
  return `<!doctype html>
<html lang="ko">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)}</title>
  <style>
    table { border-collapse: collapse; width: 100%; font-family: "Malgun Gothic", sans-serif; }
    th, td { border: 1px solid #9aa4b2; padding: 8px; vertical-align: top; mso-number-format:"\\@"; }
    th { background: #e8f1ed; font-weight: 700; }
  </style>
</head>
<body>
  <table>
    <thead><tr><th>문서</th><th>섹션</th><th>항목</th><th>내용</th></tr></thead>
    <tbody>${tableRows}</tbody>
  </table>
</body>
</html>`;
}

async function loadRhwp() {
  if (!rhwpModulePromise) {
    rhwpModulePromise = (async () => {
      let canvasContext: CanvasRenderingContext2D | null = null;
      let lastFont = "";
      globalThis.measureTextWidth = (font: string, text: string) => {
        if (!canvasContext) {
          canvasContext = document.createElement("canvas").getContext("2d");
        }
        if (!canvasContext) return text.length * 12;
        if (font !== lastFont) {
          canvasContext.font = font;
          lastFont = font;
        }
        return canvasContext.measureText(text).width;
      };

      const rhwp = await import("@rhwp/core");
      await rhwp.default({ module_or_path: "/rhwp_bg.wasm" });
      return rhwp;
    })();
  }

  return rhwpModulePromise;
}

async function buildHwpxWithRhwp(body: string) {
  const { HwpDocument } = await loadRhwp();
  const document = HwpDocument.createEmpty();
  try {
    document.createBlankDocument();
    document.insertText(0, 0, 0, body);
    const exported = document.exportHwpx();
    const buffer = new ArrayBuffer(exported.byteLength);
    new Uint8Array(buffer).set(exported);
    return new Blob([buffer], { type: "application/hwp+zip" });
  } finally {
    document.free();
  }
}

function buildCombinedText(values: Record<DocumentKey, string>) {
  return documentMeta.map((item) => `# ${item.title}\n\n${values[item.key]}`).join("\n\n---\n\n");
}

export function WorkpackEditor({ data }: { data: AskResponse }) {
  const initialValues = useMemo<Record<DocumentKey, string>>(
    () => ({
      riskAssessmentDraft: data.deliverables.riskAssessmentDraft,
      tbmBriefing: data.deliverables.tbmBriefing,
      tbmLogDraft: data.deliverables.tbmLogDraft,
      safetyEducationRecordDraft: data.deliverables.safetyEducationRecordDraft,
      kakaoMessage: data.deliverables.kakaoMessage
    }),
    [data]
  );
  const [selectedKey, setSelectedKey] = useState<DocumentKey>("riskAssessmentDraft");
  const [values, setValues] = useState<Record<DocumentKey, string>>(initialValues);
  const [hwpxStatus, setHwpxStatus] = useState<"idle" | "building" | "error">("idle");
  const [sheetStatus, setSheetStatus] = useState<"idle" | "copied" | "error">("idle");
  const selected = documentMeta.find((item) => item.key === selectedKey) || documentMeta[0];
  const selectedText = values[selected.key];
  const baseName = sanitizeFileName(`${data.scenario.companyName}-${selected.fileBase}`);

  function updateValue(value: string) {
    setValues((current) => ({ ...current, [selected.key]: value }));
  }

  function downloadText() {
    downloadBlob(new Blob([selectedText], { type: "text/plain;charset=utf-8" }), `${baseName}.txt`);
  }

  function downloadJson() {
    const payload = {
      title: selected.title,
      scenario: data.scenario,
      document: selectedText,
      generatedAt: new Date().toISOString()
    };
    downloadBlob(new Blob([JSON.stringify(payload, null, 2)], { type: "application/json;charset=utf-8" }), `${baseName}.json`);
  }

  function downloadHtml() {
    downloadBlob(new Blob([buildHtml(selected.title, selectedText)], { type: "text/html;charset=utf-8" }), `${baseName}.html`);
  }

  function downloadCsv() {
    const rows = buildRowsForDocument(selected, values);
    downloadBlob(new Blob([`\uFEFF${buildDelimited(rows, ",")}`], { type: "text/csv;charset=utf-8" }), `${baseName}.csv`);
  }

  function downloadXls() {
    const rows = buildRowsForDocument(selected, values);
    downloadBlob(new Blob([buildExcelHtml(selected.title, rows)], { type: "application/vnd.ms-excel;charset=utf-8" }), `${baseName}.xls`);
  }

  function downloadJpg() {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1240" height="1754">
      <rect width="100%" height="100%" fill="#fffaf1"/>
      <foreignObject x="60" y="60" width="1120" height="1634">
        <div xmlns="http://www.w3.org/1999/xhtml" style="font-family: 'Malgun Gothic', sans-serif; color:#1d2430;">
          <h1 style="font-size:36px;margin:0 0 24px;">${escapeHtml(selected.title)}</h1>
          <pre style="white-space:pre-wrap;font-family:inherit;font-size:22px;line-height:1.55;">${escapeHtml(selectedText)}</pre>
        </div>
      </foreignObject>
    </svg>`;
    const image = new Image();
    const svgUrl = URL.createObjectURL(new Blob([svg], { type: "image/svg+xml;charset=utf-8" }));
    image.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = 1240;
      canvas.height = 1754;
      const context = canvas.getContext("2d");
      if (!context) return;
      context.fillStyle = "#fffaf1";
      context.fillRect(0, 0, canvas.width, canvas.height);
      context.drawImage(image, 0, 0);
      canvas.toBlob((blob) => {
        if (blob) downloadBlob(blob, `${baseName}.jpg`);
        URL.revokeObjectURL(svgUrl);
      }, "image/jpeg", 0.92);
    };
    image.src = svgUrl;
  }

  async function downloadHwpx() {
    setHwpxStatus("building");
    try {
      const blob = await buildHwpxWithRhwp(`${selected.title}\n\n${selectedText}`);
      downloadBlob(blob, `${baseName}.hwpx`);
      setHwpxStatus("idle");
    } catch (error) {
      console.error("rhwp HWPX export failed", error);
      setHwpxStatus("error");
    }
  }

  function downloadAll() {
    const combined = buildCombinedText(values);
    downloadBlob(new Blob([combined], { type: "text/plain;charset=utf-8" }), `${sanitizeFileName(data.scenario.companyName)}-safeguard-workpack.txt`);
  }

  function downloadAllCsv() {
    const rows = buildRowsForAll(values);
    downloadBlob(new Blob([`\uFEFF${buildDelimited(rows, ",")}`], { type: "text/csv;charset=utf-8" }), `${sanitizeFileName(data.scenario.companyName)}-safeguard-workpack.csv`);
  }

  function downloadAllXls() {
    const rows = buildRowsForAll(values);
    downloadBlob(new Blob([buildExcelHtml("SafeGuard 문서팩", rows)], { type: "application/vnd.ms-excel;charset=utf-8" }), `${sanitizeFileName(data.scenario.companyName)}-safeguard-workpack.xls`);
  }

  async function copySheetsTsv() {
    const rows = buildRowsForAll(values);
    try {
      await navigator.clipboard.writeText(buildDelimited(rows, "\t"));
      setSheetStatus("copied");
      window.open("https://sheets.new", "_blank", "noopener,noreferrer");
    } catch (error) {
      console.error("Google Sheets TSV copy failed", error);
      setSheetStatus("error");
    }
  }

  function printPdf() {
    const popup = window.open("", "_blank", "width=900,height=1100");
    if (!popup) return;
    popup.document.write(buildHtml(selected.title, selectedText));
    popup.document.close();
    popup.focus();
    popup.print();
  }

  return (
    <section className="workpack-shell" id="workpack">
      <div className="workpack-sidebar card list">
        <div>
          <div className="eyebrow">SafeGuard Workpack</div>
          <div className="h2">오늘 문서팩</div>
          <p className="muted">현장에서 바로 수정하고 내려받을 수 있는 작업 전 산출물입니다.</p>
        </div>
        <div className="doc-tab-list">
          {documentMeta.map((item) => (
            <button
              key={item.key}
              type="button"
              className={`doc-tab ${item.key === selected.key ? "active" : ""}`}
              onClick={() => setSelectedKey(item.key)}
            >
              <strong>{item.title}</strong>
              <span>{item.description}</span>
            </button>
          ))}
        </div>
        <div className="sheet-export-panel">
          <button type="button" className="button secondary" onClick={downloadAll}>전체 TXT</button>
          <button type="button" className="button secondary" onClick={downloadAllCsv}>전체 CSV</button>
          <button type="button" className="button secondary" onClick={downloadAllXls}>전체 XLS</button>
          <button type="button" className="button" onClick={copySheetsTsv}>Google Sheets로 열기</button>
          {sheetStatus === "copied" ? <p className="muted small">시트형 TSV를 복사했습니다. 새 구글시트에 붙여넣으면 표로 들어갑니다.</p> : null}
          {sheetStatus === "error" ? <p className="export-error">클립보드 복사에 실패했습니다. CSV 또는 XLS로 내려받아 업로드해 주세요.</p> : null}
        </div>
      </div>

      <div className="card document-editor">
        <div className="document-toolbar">
          <div>
            <div className="eyebrow">Editable document</div>
            <div className="h2">{selected.title}</div>
            <p className="muted">{selected.description}</p>
          </div>
          <div className="download-bar">
            <button type="button" className="button secondary" onClick={downloadText}>TXT</button>
            <button type="button" className="button secondary" onClick={downloadJson}>JSON</button>
            <button type="button" className="button secondary" onClick={downloadCsv}>CSV</button>
            <button type="button" className="button secondary" onClick={downloadXls}>XLS</button>
            <button type="button" className="button secondary" onClick={downloadHtml}>HTML</button>
            <button type="button" className="button secondary" onClick={downloadJpg}>JPG</button>
            <button type="button" className="button secondary" onClick={printPdf}>PDF</button>
            <button type="button" className="button" onClick={downloadHwpx} disabled={hwpxStatus === "building"}>
              {hwpxStatus === "building" ? "HWPX 생성 중" : "HWPX"}
            </button>
          </div>
        </div>
        {hwpxStatus === "error" ? (
          <p className="export-error">HWPX 생성 중 오류가 발생했습니다. TXT 또는 HTML로 먼저 내려받아 주세요.</p>
        ) : null}
        <textarea
          className="document-textarea"
          value={selectedText}
          onChange={(event) => updateValue(event.target.value)}
          aria-label={`${selected.title} 편집`}
        />
      </div>
    </section>
  );
}
