export const frontendTypography = {
  fonts: {
    product: '"Pretendard", "Noto Sans KR", "Malgun Gothic", system-ui, sans-serif',
    hud: '"Geist Mono", "Cascadia Mono", Consolas, monospace',
    multilingual:
      '"Noto Sans", "Noto Sans KR", "Noto Sans Thai", "Noto Sans Khmer", "Noto Sans Myanmar", "Noto Sans Devanagari", "Malgun Gothic", sans-serif',
    document: '"Malgun Gothic", "Apple SD Gothic Neo", "Noto Sans KR", sans-serif',
  },
  screen: {
    display: { size: "clamp(44px, 6vw, 72px)", weight: 800, lineHeight: "0.98", tracking: "-0.045em" },
    pageTitle: { size: "clamp(32px, 4vw, 40px)", weight: 800, lineHeight: "1.15", tracking: "-0.035em" },
    sectionTitle: { size: "clamp(24px, 3vw, 28px)", weight: 800, lineHeight: "1.25", tracking: "-0.025em" },
    componentTitle: { size: "20px", weight: 700, lineHeight: "1.35", tracking: "-0.015em" },
    bodyLarge: { size: "17px", weight: 500, lineHeight: "1.65", tracking: "0" },
    body: { size: "15px", weight: 500, lineHeight: "1.60", tracking: "0" },
    support: { size: "14px", weight: 500, lineHeight: "1.60", tracking: "0" },
    control: { size: "14px", weight: 700, lineHeight: "20px", tracking: "0" },
    table: { size: "13px", weight: 500, lineHeight: "20px", tracking: "0" },
    caption: { size: "12px", weight: 600, lineHeight: "18px", tracking: "0" },
    hud: { size: "11px", weight: 700, lineHeight: "16px", tracking: "0.08em" },
  },
  print: {
    title: { size: "20pt", weight: 700, lineHeight: "24pt", tracking: "-0.02em" },
    section: { size: "14pt", weight: 700, lineHeight: "18pt", tracking: "-0.01em" },
    body: { size: "10pt", weight: 400, lineHeight: "15pt", tracking: "0" },
    table: { size: "8.5pt", weight: 400, lineHeight: "12pt", tracking: "0" },
    tableHeader: { size: "8.5pt", weight: 700, lineHeight: "12pt", tracking: "0" },
    note: { size: "8pt", weight: 400, lineHeight: "11pt", tracking: "0" },
  },
  cssTokens: [
    "--font-product",
    "--font-hud",
    "--font-multilingual",
    "--font-document",
    "--text-display",
    "--text-page-title",
    "--text-section-title",
    "--text-component-title",
    "--text-body-lg",
    "--text-body",
    "--text-support",
    "--text-control",
    "--text-table",
    "--text-caption",
    "--text-hud",
    "--leading-display",
    "--leading-page-title",
    "--leading-section-title",
    "--leading-component-title",
    "--leading-body-lg",
    "--leading-body",
    "--leading-longform",
    "--leading-control",
    "--leading-table",
    "--leading-caption",
    "--leading-hud",
    "--tracking-body",
    "--tracking-component-title",
    "--tracking-section-title",
    "--tracking-page-title",
    "--tracking-display",
    "--tracking-hud",
  ] as const,
} as const;

export const frontendSpacing = {
  1: "4px",
  2: "8px",
  3: "12px",
  4: "16px",
  5: "20px",
  6: "24px",
  8: "32px",
  10: "40px",
  12: "48px",
  16: "64px",
  20: "80px",
  24: "96px",
} as const;

export const frontendShape = {
  structuralRadius: "0",
  microRadius: "2px",
  controlRadius: "4px",
  panelRadius: "4px",
  circleRadius: "50%",
  controlHeight: "44px",
  compactControlHeight: "36px",
  iconHitArea: "44px",
} as const;

export const userVisibleRoutes = [
  "/",
  "/archive",
  "/ask",
  "/auth/callback",
  "/demo",
  "/dispatch",
  "/documents",
  "/dryrun",
  "/evidence",
  "/evidence-file",
  "/home",
  "/interpretation/[id]",
  "/knowledge",
  "/knowledge/[section]/[slug]",
  "/law/[id]",
  "/login",
  "/ontology",
  "/ops/api",
  "/precedent/[id]",
  "/preview",
  "/prototype",
  "/reports",
  "/roadmap",
  "/search",
  "/settings",
  "/settings/ai-connect",
  "/tbm",
  "/trust",
  "/why",
  "/worker",
  "/workers",
  "/workspace",
] as const;
export const specialSurfaceFiles = [
  "app/not-found.tsx",
  "app/error.tsx",
  "app/global-error.tsx",
  "app/workspace/loading.tsx",
] as const;

export const generatedSurfaceFiles = [
  "components/WorkpackEditor.tsx",
  "app/api/export/pdf/route.ts",
] as const;
