#!/usr/bin/env node
import childProcess from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import process from "node:process";
import { pathToFileURL } from "node:url";
import { initSync, HwpDocument } from "@rhwp/core";

const baseUrl = process.env.SAFEGUARD_BASE_URL || "https://safeguard-contest-mvp.vercel.app";
const outDir = path.resolve(process.env.SAFEGUARD_OUT_DIR || path.join(process.cwd(), "evaluation", "2026-04-29-orchestration-download-smoke"));
const chromePath = process.env.CHROME_PATH || "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";
const question = process.env.SAFEGUARD_SMOKE_QUESTION || "대구 달서구 창고업 고중량 박스 적재 및 수작업 운반. 작업자 5명, 숙련자 중심, 오늘 날씨를 반영해 위험성평가와 TBM, 안전보건교육 기록을 만들어줘.";

const documentMeta = [
  ["workpackSummaryDraft", "점검결과 요약", "workpack-summary"],
  ["riskAssessmentDraft", "위험성평가표", "risk-assessment"],
  ["workPlanDraft", "작업계획서", "work-plan"],
  ["tbmBriefing", "TBM/작업 전 안전점검회의", "tbm-briefing"],
  ["tbmLogDraft", "TBM 기록", "tbm-log"],
  ["safetyEducationRecordDraft", "안전보건교육 기록", "safety-education"],
  ["emergencyResponseDraft", "비상대응 절차", "emergency-response"],
  ["photoEvidenceDraft", "사진/증빙", "photo-evidence"],
  ["foreignWorkerBriefing", "외국인 근로자 출력본", "foreign-worker-briefing"],
  ["foreignWorkerTransmission", "외국인 근로자 전송본", "foreign-worker-message"],
  ["kakaoMessage", "현장 공유 메시지", "field-message"],
];

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function sanitizeFileName(value) {
  return value.replace(/[\\/:*?"<>|]/g, "-").replace(/\s+/g, "-").slice(0, 80) || "safeguard";
}

function escapeHtml(value) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function parseSheetRows(title, body) {
  const rows = [];
  let section = "기본정보";
  let itemNumber = 1;

  body.split(/\r?\n/).forEach((rawLine) => {
    const line = rawLine.trim();
    if (!line) return;

    const sectionMatch = line.match(/^\[(.+)\]$/);
    if (sectionMatch) {
      section = sectionMatch[1];
      itemNumber = 1;
      return;
    }

    const keyed = line.match(/^([^:：]+)[:：]\s*(.+)$/);
    const numbered = line.match(/^(\d+)\.\s*(.+)$/);
    const bullet = line.match(/^[-ㆍ]\s*(.+)$/);

    if (keyed) {
      rows.push({ document: title, section, item: keyed[1].trim(), content: keyed[2].trim() });
      return;
    }
    if (numbered) {
      rows.push({ document: title, section, item: numbered[1].trim(), content: numbered[2].trim() });
      return;
    }
    if (bullet) {
      rows.push({ document: title, section, item: String(itemNumber), content: bullet[1].trim() });
      itemNumber += 1;
      return;
    }

    rows.push({ document: title, section, item: String(itemNumber), content: line });
    itemNumber += 1;
  });

  return rows;
}

function escapeCell(value) {
  return `"${value.replace(/"/g, "\"\"")}"`;
}

function buildDelimited(rows, delimiter) {
  const header = ["문서", "섹션", "항목", "내용"];
  const body = rows.map((row) => [row.document, row.section, row.item, row.content]
    .map((value) => delimiter === "," ? escapeCell(value) : value.replace(/\t/g, " ").replace(/\r?\n/g, " "))
    .join(delimiter));
  return [header.join(delimiter), ...body].join("\n");
}

function buildHtml(title, body) {
  return `<!doctype html>
<html lang="ko">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)}</title>
  <style>
    body { font-family: "Noto Sans KR", "Malgun Gothic", sans-serif; color: #1d2430; margin: 40px; line-height: 1.65; letter-spacing: .01em; }
    h1 { font-size: 24px; margin: 0 0 18px; }
    pre { white-space: pre-wrap; font-family: inherit; font-size: 14px; }
    .meta { color: #657084; font-size: 12px; margin-bottom: 22px; }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  <div class="meta">Generated by SafeGuard</div>
  <pre>${escapeHtml(body)}</pre>
</body>
</html>`;
}

function buildExcelHtml(title, rows) {
  const grouped = rows.reduce((acc, row) => {
    acc[row.section] = [...(acc[row.section] || []), row];
    return acc;
  }, {});
  const summaryRows = Object.entries(grouped).map(([section, sectionRows]) => `
    <tr>
      <td>${escapeHtml(section)}</td>
      <td>${sectionRows.length}</td>
      <td>${escapeHtml(sectionRows.slice(0, 2).map((row) => row.item).join(", "))}</td>
    </tr>
  `).join("");
  const tableRows = Object.entries(grouped).map(([section, sectionRows]) => `
    <tr class="section-row"><td colspan="4">${escapeHtml(section)}</td></tr>
    ${sectionRows.map((row, index) => `<tr><td class="center">${index + 1}</td><td>${escapeHtml(row.item)}</td><td>${escapeHtml(row.content)}</td><td class="check-cell">□ 확인</td></tr>`).join("")}
  `).join("");
  return `<!doctype html>
<html lang="ko">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)}</title>
  <style>
    body { font-family: "Malgun Gothic", "Noto Sans KR", sans-serif; color: #17201d; }
    .cover { border: 2px solid #1f4d43; background: #e8f1ed; padding: 18px; margin-bottom: 14px; }
    .cover h1 { margin: 0 0 8px; font-size: 22px; }
    .cover p { margin: 0; color: #5e6677; }
    table { border-collapse: collapse; width: 100%; table-layout: fixed; font-family: "Malgun Gothic", sans-serif; margin-bottom: 14px; }
    th, td { border: 1px solid #9aa4b2; padding: 8px; vertical-align: top; mso-number-format:"\\@"; word-break: keep-all; }
    th { background: #1f4d43; color: #ffffff; font-weight: 700; text-align: center; }
    .summary th { background: #6f4b26; }
    .section-row td { background: #e8f1ed; color: #1f4d43; font-weight: 700; font-size: 14px; border-top: 2px solid #1f4d43; }
    .center { text-align: center; width: 42px; }
    .check-cell { text-align: center; color: #6f4b26; width: 90px; }
    .note { color: #5e6677; font-size: 12px; margin-top: 10px; }
  </style>
</head>
<body>
  <div class="cover">
    <h1>${escapeHtml(title)}</h1>
    <p>SafeGuard 현장 문서팩 · 검토/확인/서명용 Excel 서식</p>
  </div>
  <table class="summary">
    <colgroup><col style="width: 34%;" /><col style="width: 12%;" /><col style="width: 54%;" /></colgroup>
    <thead><tr><th>섹션</th><th>항목 수</th><th>주요 항목</th></tr></thead>
    <tbody>${summaryRows}</tbody>
  </table>
  <table>
    <colgroup><col style="width: 6%;" /><col style="width: 22%;" /><col style="width: 60%;" /><col style="width: 12%;" /></colgroup>
    <thead><tr><th>No.</th><th>항목</th><th>내용</th><th>확인</th></tr></thead>
    <tbody>${tableRows}</tbody>
  </table>
  <p class="note">본 파일은 공식자료 기반 초안입니다. 현장관리자가 작업 전 최종 확인 후 사용하세요.</p>
</body>
</html>`;
}

function buildWordHtml(title, rows) {
  const grouped = rows.reduce((acc, row) => {
    acc[row.section] = [...(acc[row.section] || []), row];
    return acc;
  }, {});
  const sections = Object.entries(grouped).map(([section, sectionRows]) => `
    <h2>${escapeHtml(section)}</h2>
    <table>
      <thead><tr><th style="width: 24%;">항목</th><th>내용</th></tr></thead>
      <tbody>${sectionRows.map((row) => `<tr><td>${escapeHtml(row.item)}</td><td>${escapeHtml(row.content)}</td></tr>`).join("")}</tbody>
    </table>
  `).join("");

  return `<!doctype html>
<html lang="ko">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)}</title>
  <style>
    body { font-family: "Malgun Gothic", "Noto Sans KR", sans-serif; margin: 34px; color: #1d2430; line-height: 1.6; }
    h1 { margin: 0 0 8px; font-size: 24px; }
    h2 { margin: 24px 0 8px; font-size: 16px; border-left: 4px solid #21594f; padding-left: 8px; }
    table { border-collapse: collapse; width: 100%; margin-bottom: 12px; }
    th, td { border: 1px solid #9aa4b2; padding: 9px; vertical-align: top; font-size: 13px; }
    th { background: #e8f1ed; }
    .meta { color: #657084; margin-bottom: 18px; font-size: 12px; }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  <div class="meta">SafeGuard 공식자료 기반 초안 · 현장 검토 후 사용</div>
  ${sections}
</body>
</html>`;
}

function buildHwpTemplateText(title, rows) {
  const grouped = rows.reduce((acc, row) => {
    acc[row.section] = [...(acc[row.section] || []), row];
    return acc;
  }, {});

  return [
    `${title}(초안)`,
    "SafeGuard 공식자료 기반 서식 · 현장 검토 후 사용",
    "",
    ...Object.entries(grouped).flatMap(([section, sectionRows]) => [
      `[${section}]`,
      ...sectionRows.map((row) => `${row.item}. ${row.content}`),
      ""
    ]),
    "[확인/서명]",
    "작성자: ____________________",
    "관리감독자: ____________________",
    "교육/TBM 확인자: ____________________",
    "보관 위치: ____________________",
    "확인일시: ______년 ____월 ____일 ____시 ____분"
  ].join("\n");
}

function buildHwpx(body) {
  globalThis.measureTextWidth = (_font, text) => text.length * 12;
  const wasm = fs.readFileSync(path.join(process.cwd(), "node_modules", "@rhwp", "core", "rhwp_bg.wasm"));
  initSync({ module: wasm });
  const document = HwpDocument.createEmpty();
  try {
    document.createBlankDocument();
    document.insertText(0, 0, 0, body);
    return Buffer.from(document.exportHwpx());
  } finally {
    document.free();
  }
}

function findChrome() {
  const candidates = [
    chromePath,
    "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
    path.join(process.env.LOCALAPPDATA || "", "Google", "Chrome", "Application", "chrome.exe")
  ];
  return candidates.find((candidate) => candidate && fs.existsSync(candidate));
}

function runChrome(args) {
  const executable = findChrome();
  if (!executable) {
    throw new Error("Chrome executable not found. Set CHROME_PATH to run PDF/JPG export smoke.");
  }
  childProcess.execFileSync(executable, args, { stdio: "ignore" });
}

function waitForFile(pathToCheck, minBytes = 1, timeoutMs = 5000) {
  const startedAt = Date.now();
  while (Date.now() - startedAt < timeoutMs) {
    if (sizeOf(pathToCheck) >= minBytes) return true;
    Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 100);
  }
  return sizeOf(pathToCheck) >= minBytes;
}

async function fetchJson(url, init) {
  const startedAt = Date.now();
  const response = await fetch(url, init);
  const text = await response.text();
  let parsed = null;
  try {
    parsed = JSON.parse(text);
  } catch {
    parsed = null;
  }
  return { status: response.status, ok: response.ok, elapsedMs: Date.now() - startedAt, parsed, rawPreview: text.slice(0, 240) };
}

function sizeOf(filePath) {
  return fs.existsSync(filePath) ? fs.statSync(filePath).size : 0;
}

function buildApiMapping(weather, ask) {
  const externalData = ask.externalData || {};
  const deliverables = ask.deliverables || {};
  const citations = Array.isArray(ask.citations) ? ask.citations : [];
  const sourceMix = ask.sourceMix || {};
  return [
    {
      source: "기상청 현재/초단기/단기/특보/영향예보",
      callPath: ["/api/weather 선조회", "/api/ask 내부 fetchWeatherSignal"],
      mode: externalData.weather?.mode || weather.weather?.mode || "unknown",
      reflectedIn: ["현장 브리프 날씨", "위험성평가표 작업조건", "TBM 기상 신호", "작업중지 기준"],
      evidence: externalData.weather?.summary || weather.weather?.summary || "",
      count: Array.isArray(externalData.weather?.signals) ? externalData.weather.signals.length : 0
    },
    {
      source: "Law.go + korean-law-mcp",
      callPath: ["/api/ask 내부 searchLegalSources"],
      mode: ask.status?.lawgo || ask.mode || "unknown",
      reflectedIn: ["근거 출처", "위험성평가표 반영 근거", "TBM 기록 반영 근거", "사진/증빙 확인 근거"],
      evidence: sourceMix.koreanLawMcp?.summary || ask.status?.detail || "",
      count: citations.length
    },
    {
      source: "Gemini",
      callPath: ["/api/ask 내부 generateAnswer"],
      mode: ask.status?.ai || ask.mode || "unknown",
      reflectedIn: ["점검결과 요약", "위험성평가표", "TBM", "안전보건교육", "외국인 전송본"],
      evidence: ask.answer?.slice(0, 160) || "",
      count: Object.values(deliverables).filter((value) => typeof value === "string" && value.length > 0).length
    },
    {
      source: "Work24 훈련과정",
      callPath: ["/api/ask 내부 fetchTrainingRecommendations"],
      mode: externalData.training?.mode || "unknown",
      reflectedIn: ["후속 교육", "안전보건교육 기록", "교육 추천 카드"],
      evidence: externalData.training?.detail || "",
      count: Array.isArray(externalData.training?.recommendations) ? externalData.training.recommendations.length : 0
    },
    {
      source: "KOSHA 안전보건교육포털",
      callPath: ["/api/ask 내부 fetchKoshaEducationRecommendations"],
      mode: externalData.koshaEducation?.mode || "unknown",
      reflectedIn: ["후속 교육", "안전보건교육 기록", "KOSHA 교육 카드"],
      evidence: externalData.koshaEducation?.detail || "",
      count: Array.isArray(externalData.koshaEducation?.recommendations) ? externalData.koshaEducation.recommendations.length : 0
    },
    {
      source: "KOSHA 공식자료/가이드",
      callPath: ["/api/ask 내부 fetchKoshaReferences"],
      mode: externalData.kosha?.mode || "unknown",
      reflectedIn: ["위험성평가 절차", "TBM 기록 항목", "안전보건교육 서식"],
      evidence: externalData.kosha?.detail || "",
      count: Array.isArray(externalData.kosha?.references) ? externalData.kosha.references.length : 0
    },
    {
      source: "KOSHA 스마트검색/자료링크/MSDS/건설업 일별 중대재해",
      callPath: ["/api/ask 내부 fetchKoshaOpenApiEvidence"],
      mode: externalData.koshaOpenApi?.mode || "unknown",
      reflectedIn: ["문서 반영 근거", "위험성평가표", "안전보건교육", "TBM"],
      evidence: externalData.koshaOpenApi?.detail || "",
      count: Array.isArray(externalData.koshaOpenApi?.references) ? externalData.koshaOpenApi.references.length : 0
    },
    {
      source: "KOSHA 국내재해사례/첨부파일/사고사망",
      callPath: ["/api/ask 내부 fetchAccidentCases"],
      mode: externalData.accidentCases?.mode || "unknown",
      reflectedIn: ["유사 재해사례", "TBM 예방 포인트", "교육 사례"],
      evidence: externalData.accidentCases?.detail || "",
      count: Array.isArray(externalData.accidentCases?.cases) ? externalData.accidentCases.cases.length : 0
    }
  ];
}

function writeDownloads(ask, filesDir) {
  const company = sanitizeFileName(ask.scenario?.companyName || "safeguard");
  const values = Object.fromEntries(documentMeta.map(([key]) => [key, ask.deliverables?.[key] || ""]));
  const sampleMeta = documentMeta[1];
  const sampleTitle = sampleMeta[1];
  const sampleBody = values[sampleMeta[0]];
  const rows = parseSheetRows(sampleTitle, sampleBody);
  const html = buildHtml(sampleTitle, sampleBody);
  const htmlPath = path.join(filesDir, `${company}-${sampleMeta[2]}.html`);
  const outputs = [
    { format: "TXT", path: path.join(filesDir, `${company}-${sampleMeta[2]}.txt`), write: () => fs.writeFileSync(path.join(filesDir, `${company}-${sampleMeta[2]}.txt`), sampleBody, "utf8") },
    { format: "JSON", path: path.join(filesDir, `${company}-${sampleMeta[2]}.json`), write: () => fs.writeFileSync(path.join(filesDir, `${company}-${sampleMeta[2]}.json`), JSON.stringify({ title: sampleTitle, scenario: ask.scenario, document: sampleBody, generatedAt: new Date().toISOString() }, null, 2), "utf8") },
    { format: "CSV", path: path.join(filesDir, `${company}-${sampleMeta[2]}.csv`), write: () => fs.writeFileSync(path.join(filesDir, `${company}-${sampleMeta[2]}.csv`), `\uFEFF${buildDelimited(rows, ",")}`, "utf8") },
    { format: "XLS", path: path.join(filesDir, `${company}-${sampleMeta[2]}.xls`), write: () => fs.writeFileSync(path.join(filesDir, `${company}-${sampleMeta[2]}.xls`), buildExcelHtml(sampleTitle, rows), "utf8") },
    { format: "DOC", path: path.join(filesDir, `${company}-${sampleMeta[2]}.doc`), write: () => fs.writeFileSync(path.join(filesDir, `${company}-${sampleMeta[2]}.doc`), buildWordHtml(sampleTitle, rows), "utf8") },
    { format: "HTML", path: htmlPath, write: () => fs.writeFileSync(htmlPath, html, "utf8") },
    { format: "HWPX", path: path.join(filesDir, `${company}-${sampleMeta[2]}.hwpx`), write: () => fs.writeFileSync(path.join(filesDir, `${company}-${sampleMeta[2]}.hwpx`), buildHwpx(buildHwpTemplateText(sampleTitle, rows))) }
  ];

  outputs.forEach((item) => item.write());

  const pdfPath = path.join(filesDir, `${company}-${sampleMeta[2]}.pdf`);
  const jpgPath = path.join(filesDir, `${company}-${sampleMeta[2]}.jpg`);
  const userDataDir = path.join(os.tmpdir(), `safeguard-chrome-${Date.now()}`);
  runChrome(["--headless=new", "--disable-gpu", "--no-sandbox", `--user-data-dir=${userDataDir}`, `--print-to-pdf=${pdfPath}`, pathToFileURL(htmlPath).href]);
  waitForFile(pdfPath, 1000);
  runChrome(["--headless=new", "--disable-gpu", "--no-sandbox", `--user-data-dir=${userDataDir}`, "--window-size=1240,1754", `--screenshot=${jpgPath}`, pathToFileURL(htmlPath).href]);
  waitForFile(jpgPath, 1000);

  const allRows = documentMeta.flatMap(([key, title]) => parseSheetRows(title, values[key]));
  const allTxtPath = path.join(filesDir, `${company}-safeguard-workpack.txt`);
  const allCsvPath = path.join(filesDir, `${company}-safeguard-workpack.csv`);
  const allXlsPath = path.join(filesDir, `${company}-safeguard-workpack.xls`);
  fs.writeFileSync(allTxtPath, documentMeta.map(([key, title]) => `# ${title}\n\n${values[key]}`).join("\n\n---\n\n"), "utf8");
  fs.writeFileSync(allCsvPath, `\uFEFF${buildDelimited(allRows, ",")}`, "utf8");
  fs.writeFileSync(allXlsPath, buildExcelHtml("SafeGuard 문서팩", allRows), "utf8");

  return [
    ...outputs.map((item) => ({ format: item.format, file: path.relative(process.cwd(), item.path), bytes: sizeOf(item.path), ok: sizeOf(item.path) > 100 })),
    { format: "PDF", file: path.relative(process.cwd(), pdfPath), bytes: sizeOf(pdfPath), ok: sizeOf(pdfPath) > 1000 },
    { format: "JPG", file: path.relative(process.cwd(), jpgPath), bytes: sizeOf(jpgPath), ok: sizeOf(jpgPath) > 1000 },
    { format: "ALL_TXT", file: path.relative(process.cwd(), allTxtPath), bytes: sizeOf(allTxtPath), ok: sizeOf(allTxtPath) > 100 },
    { format: "ALL_CSV", file: path.relative(process.cwd(), allCsvPath), bytes: sizeOf(allCsvPath), ok: sizeOf(allCsvPath) > 100 },
    { format: "ALL_XLS", file: path.relative(process.cwd(), allXlsPath), bytes: sizeOf(allXlsPath), ok: sizeOf(allXlsPath) > 100 }
  ];
}

ensureDir(outDir);
const filesDir = path.join(outDir, "files");
ensureDir(filesDir);

const startedAt = Date.now();
const weatherUrl = `${baseUrl}/api/weather?question=${encodeURIComponent(question)}`;
const weatherResult = await fetchJson(weatherUrl);
const askResult = await fetchJson(`${baseUrl}/api/ask`, {
  method: "POST",
  headers: { "content-type": "application/json" },
  body: JSON.stringify({ question })
});

if (!weatherResult.ok || !weatherResult.parsed?.weather) {
  throw new Error(`Weather preflight failed: ${weatherResult.status} ${weatherResult.rawPreview}`);
}
if (!askResult.ok || !askResult.parsed?.deliverables) {
  throw new Error(`Ask orchestration failed: ${askResult.status} ${askResult.rawPreview}`);
}

const apiMapping = buildApiMapping(weatherResult.parsed, askResult.parsed);
const downloads = writeDownloads(askResult.parsed, filesDir);
const failCount = downloads.filter((item) => !item.ok).length;
const summary = {
  baseUrl,
  generatedAt: new Date().toISOString(),
  elapsedMs: Date.now() - startedAt,
  question,
  weather: {
    status: weatherResult.status,
    elapsedMs: weatherResult.elapsedMs,
    mode: weatherResult.parsed.weather.mode,
    summary: weatherResult.parsed.weather.summary,
    signalCount: Array.isArray(weatherResult.parsed.weather.signals) ? weatherResult.parsed.weather.signals.length : 0
  },
  ask: {
    status: askResult.status,
    elapsedMs: askResult.elapsedMs,
    mode: askResult.parsed.mode,
    statusSummary: askResult.parsed.status?.summary || "",
    documentCount: documentMeta.filter(([key]) => typeof askResult.parsed.deliverables?.[key] === "string" && askResult.parsed.deliverables[key].length > 0).length
  },
  apiMapping,
  downloads,
  ok: failCount === 0,
  failCount
};

const report = [
  "# SafeGuard API 조합 및 다운로드 스모크",
  "",
  `- 생성시각: ${summary.generatedAt}`,
  `- 대상 URL: ${baseUrl}`,
  `- 질문: ${question}`,
  `- 기상 선조회: ${summary.weather.mode} / ${summary.weather.summary}`,
  `- /api/ask: ${summary.ask.mode} / 문서 ${summary.ask.documentCount}종`,
  "",
  "## API 반영 맵",
  "",
  "| API | 호출 경로 | 상태 | 반영 위치 | 건수/신호 | 증거 |",
  "| --- | --- | --- | --- | ---: | --- |",
  ...apiMapping.map((item) => `| ${item.source} | ${item.callPath.join("<br>")} | ${item.mode} | ${item.reflectedIn.join("<br>")} | ${item.count} | ${String(item.evidence).replace(/\|/g, "/").slice(0, 160)} |`),
  "",
  "## 다운로드 생성 결과",
  "",
  "| 형식 | 결과 | 바이트 | 파일 |",
  "| --- | --- | ---: | --- |",
  ...downloads.map((item) => `| ${item.format} | ${item.ok ? "ok" : "fail"} | ${item.bytes} | ${item.file} |`)
].join("\n");

fs.writeFileSync(path.join(outDir, "api-orchestration-download-smoke.json"), JSON.stringify(summary, null, 2), "utf8");
fs.writeFileSync(path.join(outDir, "api-orchestration-download-smoke.md"), report, "utf8");
console.log(JSON.stringify({
  ok: summary.ok,
  outDir: path.relative(process.cwd(), outDir),
  weatherMode: summary.weather.mode,
  askMode: summary.ask.mode,
  documentCount: summary.ask.documentCount,
  downloadCount: downloads.length,
  failCount
}, null, 2));
process.exit(summary.ok ? 0 : 1);
